### ISSUE TITLE
Use it with Spark?

### ISSUE THREAD

**Issue by maxliu** [cgnorthcutt/rankpruning#2]
Hi, 

Thanks for sharing such cool tool. Any thoughts / plan for using it with spark? So it can be used handling bigger data set.

Thanks,
-Max

**Comment by cgnorthcutt** [comment]
Hi, hope you're enjoying this package (rankpruning), which is NOW DEPRECATED. It has been replaced by https://github.com/cgnorthcutt/cleanlab -- which generalizes the package to multi-class learning with noisy labels and supports a wide range of functions for identifying label errors in datasets. You'll want to make the switch as soon as possible. Unlike rankpruning, the cleanlab package supports Python 2 and 3 and has professional support for testing with tox/travisCI/coverage/pytest.
