### ISSUE TITLE
issue with import again

### ISSUE THREAD

**Issue by aagq** [cgnorthcutt/rankpruning#4]
Hi!
I have some trouble with the import 
$ ipython
Python 3.6.1 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:09:58) 
Type "copyright", "credits" or "license" for more information.

IPython 5.3.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

from rankpruning import RankPruning, other_pnlearning_methods
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-228227c6b4e6> in <module>()
----> 1 from rankpruning import RankPruning, other_pnlearning_methods

/home/agq/Documents/rankpruning/rankpruning-master/rankpruning/other_pnlearning_methods.py in <module>()
      7 from sklearn.linear_model import LogisticRegression as logreg
      8 from sklearn.model_selection import train_test_split
----> 9 from rankpruning import assert_inputs_are_valid, compute_cv_predicted_probabilities as cv_pred_proba
     10 
     11 

ImportError: cannot import name 'assert_inputs_are_valid'

hope you can help,
many thanks,
June

**Comment by 51616** [comment]
I added methods in rankpruning.py into other_pnlearning_methods.py should solve the problem or you can just ignore that file completely 'cause it is used only to demonstrate test file.

Rank Pruning method only uses rankpruning.py but there are some syntax error/bugs in some methods in the file you should easily fix it before installing or try to create RankPruning model and read the error messages then fix them one by one.

**Comment by cgnorthcutt** [comment]
Hi, hope you're enjoying this package (rankpruning), which is NOW DEPRECATED. It has been replaced by https://github.com/cgnorthcutt/cleanlab -- which generalizes the package to multi-class learning with noisy labels and supports a wide range of functions for identifying label errors in datasets. You'll want to make the switch as soon as possible. Unlike rankpruning, the cleanlab package supports Python 2 and 3 and has professional support for testing with tox/travisCI/coverage/pytest.
