### ISSUE TITLE
About classifier that used as RP clf parameter

### ISSUE THREAD

**Issue by 51616** [cgnorthcutt/rankpruning#5]
Should I train the classifier model with subset of the whole data first or just used the vanilla classifier model with default settings as clf parameter. And should i tune the model parameter setting at all? 

PS. Do you have other evaluation methods to use with PU or (P^)(N^) learning? currently i am using F1 score and classification report which i think is might not be accurate and interpretable in PU learning.

Thanks in advance for your answer. :)

**Comment by cgnorthcutt** [comment]
Hi, hope you're enjoying this package (rankpruning), which is NOW DEPRECATED. It has been replaced by https://github.com/cgnorthcutt/cleanlab -- which generalizes the package to multi-class learning with noisy labels and supports a wide range of functions for identifying label errors in datasets. You'll want to make the switch as soon as possible. Unlike rankpruning, the cleanlab package supports Python 2 and 3 and has professional support for testing with tox/travisCI/coverage/pytest.

note that cleanlab lets you choose the score function you'd like to use :) Also check out https://github.com/cgnorthcutt/hypopt for an easy way to tune your classifier with any score function you like.
